/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SedesSlugRouteImport } from './routes/sedes.$slug'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SedesSlugRoute = SedesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SedesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/sedes': typeof SedesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/testimonios': typeof TestimoniosRoute
  '/sedes/$slug': typeof SedesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/sedes': typeof SedesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/testimonios': typeof TestimoniosRoute
  '/sedes/$slug': typeof SedesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/sedes': typeof SedesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/testimonios': typeof TestimoniosRoute
  '/sedes/$slug': typeof SedesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contacto'
    | '/planes'
    | '/sedes'
    | '/sitemap.xml'
    | '/staff'
    | '/testimonios'
    | '/sedes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contacto'
    | '/planes'
    | '/sedes'
    | '/sitemap.xml'
    | '/staff'
    | '/testimonios'
    | '/sedes/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contacto'
    | '/planes'
    | '/sedes'
    | '/sitemap.xml'
    | '/staff'
    | '/testimonios'
    | '/sedes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactoRoute: typeof ContactoRoute
  PlanesRoute: typeof PlanesRoute
  SedesRoute: typeof SedesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRoute
  TestimoniosRoute: typeof TestimoniosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedes/$slug': {
      id: '/sedes/$slug'
      path: '/$slug'
      fullPath: '/sedes/$slug'
      preLoaderRoute: typeof SedesSlugRouteImport
      parentRoute: typeof SedesRoute
    }
  }
}

interface SedesRouteChildren {
  SedesSlugRoute: typeof SedesSlugRoute
}

const SedesRouteChildren: SedesRouteChildren = {
  SedesSlugRoute: SedesSlugRoute,
}

const SedesRouteWithChildren = SedesRoute._addFileChildren(SedesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactoRoute: ContactoRoute,
  PlanesRoute: PlanesRoute,
  SedesRoute: SedesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRoute,
  TestimoniosRoute: TestimoniosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
